CC = gcc
all: p2-dogServer.c ./SourceCode/general.c ./SourceCode/uno.c ./SourceCode/dos.c ./SourceCode/tres.c ./SourceCode/cuatro.c
	@ $(CC) -IHeaders p2-dogServer.c ./SourceCode/general.c ./SourceCode/uno.c ./SourceCode/dos.c ./SourceCode/tres.c ./SourceCode/cuatro.c -o p2-dogServer -lncurses